### ISSUE TITLE
 `set-env` command to be disabled soon

### ISSUE THREAD

**Issue by aniketmitra001** [lukka/set-shell-env#7]
We use the ```set-shell-env``` action in our [workflow](https://github.com/heremaps/movetk/blob/master/.github/workflows/build-windows.yml) 

When the workflow runs, we get the following message 

```The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/```

Are there any plans to support this action after the ```set-env``` command is disabled?

**Comment by rm5248** [comment]
It looks like all that needs to happen is to do a new release, at least according to [this comment](https://github.com/actions/toolkit/issues/630#issuecomment-726152106).  The update to 1.2.6 was done on October 1 by Dependabot.

**Comment by lukka** [comment]
Released https://github.com/lukka/set-shell-env/releases/tag/v1.1 with the fix.
